name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Google Cloud CLI
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }} # Add your GCP service account JSON key to GitHub secrets
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Authenticate Docker with Artifact Registry
    - name: Authenticate Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    # Build and tag the Docker image
    - name: Build Docker Image
      run: docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloudrun-images/hello-world-app:latest .

    # Push the Docker image to Google Artifact Registry
    - name: Push Docker Image
      run: docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloudrun-images/hello-world-app:latest

    # Deploy the application to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy hello-world-app \
          --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloudrun-images/hello-world-app:latest \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated
